CUDA_VISIBLE_DEVICES=0 python fluo_recon_root.py \
    --data_name Roots_xyScan_128.tif \
    --exp_psf_name ExpPSF_605.mat \
    --show_inter_imgs True \
    --model_opt "complie" \
    --if_log True \
    --wavelength 605e-9 \
    --lr_psf 8e-3 \
    --num_iters 100 \
    --init_epochs 100 \
    --learn_psf_epochs 150 \
    --z_dim 8 \
    --z_sep 0.1 \
    --l1_g 0 \
    --l1_z 0
